### ISSUE TITLE
eventlistener/event-listener.go not working as expected

### ISSUE THREAD

**Issue by surajsprabhu** [tsaridas/salt-event-listener-golang#2]
On executing,
**go run eventlistener/event-listener.go** getting error as below:
```
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
main.reader(0x7f53414c4ff8, 0xc000010038)
        /home/saltuser/goworkspace/src/salt-golang/eventlistener/event-listener.go:17 +0x340
main.main()
        /home/saltuser/goworkspace/src/salt-golang/eventlistener/event-listener.go:38 +0x136
exit status 2
```

Added a condition to prevent this issue from occurring:
```
dec.Decode(&m1)
if len(m1) == 0 {
        continue
}
m1_1 := m1["body"].(string)
```

Once this condition is added, the error doesn't occur any more. However, the script simply keeps running and nothing is displayed even when a salt event is fired.

**Comment by tsaridas** [comment]
which version of salt are you running ? asking because I haven't tested on the latest version and they might have changed something.

**Comment by surajsprabhu** [comment]
It's salt 2015.5.10

**Comment by tsaridas** [comment]
I need to find some time to test with the version. listener is pretty simple and just unpacks from msgpack so I would suppose there is something wrong with salt version or with your msgpack library.

I'll try to find some time during the w/e to troubleshoot.

**Comment by pgonzalezgebo** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @jwcastillo, @calvinturner, @Gennttii, @jryals579, @iamlos, @mamphis, @bebetoaze
